name = "growmyoss-analytics"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
OPENAI_MODEL = "gpt-4o-mini"

[[d1_databases]]
binding = "DB"
database_name = "analytics"
# NOTE: Replace with your real Cloudflare D1 database_id after `wrangler d1 create analytics`
database_id = "59e8149d-41c1-4de0-85a3-1e77e61ace55"